name: Elixir Build and Check
on:
  workflow_call:
    inputs:
      elixir-version:
        required: true
        type: string
      erlang-version:
        required: true
        type: string
      mix-env:
        required: false
        type: string
        default: dev
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  dependencies:
    name: Build and Cache Dependencies
    runs-on: ${{ inputs.runs-on }}
    container: ubuntu:latest
    outputs:
      cache-key-suffix: ${{ steps.build-cache-deps.outputs.cache-key-suffix }}
    steps:
      - id: build-cache-deps
        uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
          github-token: ${{ secrets.GHCR_USER_PAT }}
  credo:
    name: Credo
    needs: [dependencies]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
          github-token: ${{ secrets.GHCR_USER_PAT }}
      - run: mix do compile --force, credo --strict
  dialyzer:
    name: Dialyzer
    needs: [dependencies]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
          github-token: ${{ secrets.GHCR_USER_PAT }}
      - name: Cache PLT files
        uses: actions/cache@v3
        with:
          key: cache-plt_${{ needs.dependencies.outputs.cache-key-suffix }}
          path: |
            _build/dev/*.plt
            _build/dev/*.plt.hash
      - run: mix do compile --force, dialyzer
  dependency-audit:
    name: Dependency Audit
    needs: [dependencies]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
          github-token: ${{ secrets.GHCR_USER_PAT }}
      - name: Check for unused dependencies
        if: always()
        run: mix deps.unlock --check-unused
      - name: Check for deprecated packages
        if: always()
        run: mix hex.audit
  xref:
    name: Xref
    needs: [dependencies]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
      - name: Check for circular dependencies between modules
        run: mix xref graph --format cycles --fail-above 0 --label compile-connected
  format:
    name: Mix Format
    needs: [dependencies]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Fetch the full repository so we can perform a Git diff
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch dependencies as they may be needed by the formatter
        uses: rentpath/actions-services-elixir-deps@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          erlang-version: ${{ inputs.erlang-version }}
          mix-env: ${{ inputs.mix-env }}
          skip-checkout: 'true'
      - name: Check formatting for Elixir files that have changed
        run: |
          default_branch_ref="origin/${{ github.event.repository.default_branch }}"
          git diff --name-only "$default_branch_ref" | \
          egrep '(\.ex|\.exs)+$' | \
          xargs --no-run-if-empty mix format --check-formatted --dry-run
